epochs: 310
T: 2
model: ms_resnet34_qs
T_c_config: [2,2,2,4]
resume: output/train/20240826-172209-ms_resnet34_qs-32/model_best.pth.tar
no_resume_opt: True
lr: 1e-5
min_lr: 1e-7
device : 0
data_dir: /HDD/dataset/
dataset: torch/cifar100
num_classes: 100
img_size: 32
mean:
    - 0.4914
    - 0.4822
    - 0.4465
std:
    - 0.2470
    - 0.2435
    - 0.2616
crop_pct: 1.0
scale:
    - 1.0
    - 1.0
ratio: [1.0,1.0]
color_jitter: 0.
interpolation: bicubic
train_interpolation: bicubic
aa: rand-m9-n1-mstd0.4-inc1
mixup: 0.5
mixup_off_epoch: 200
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 0.0
reprob: 0.25
remode: const
amp: False
batch_size: 256
val_batch_size: 256
sched: cosine
weight_decay: 5e-4
cooldown_epochs: 20
warmup_epochs: 0
warmup_lr: 0.00001
opt: sgd
smoothing: 0.1
workers: 8

